### ISSUE TITLE
no error message when helm cmd fails

### ISSUE THREAD

**Issue by ninaholm** [tonsV2/helmstack#1]
Shell command: helm --kube-context ml-dev upgrade underskrift-detektor-env-v2 erst/underskrift-detektor-envjdhkgbjskdbgkldsjg --namespace dokument-redskaber --version 1.1.0 --recreate-pods --force --install

**Comment by tonsV2** [comment]
If python3 is used the error handling code work as intent. Version 1.3.0 of helmstack list python3 as a requirement.

The error handling code could definitely be better. But unless a pull request is received this will have to do for now.
